# Generated by Django 2.2.7 on 2020-04-09 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200409_1028'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
