# Generated by Django 2.2.7 on 2020-04-10 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_delete_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='link',
            field=models.TextField(blank=True, default='#', null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='link_name',
            field=models.CharField(blank=True, default='no more link', max_length=50, null=True),
        ),
    ]
