# Generated by Django 2.2.7 on 2020-04-11 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
    ]
