# Generated by Django 2.2.7 on 2020-04-13 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_like'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
